/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SplatRouteImport } from "./routes/$"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as AccountSetupRouteImport } from "./routes/account-setup"
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as AppAdminsRouteImport } from "./routes/_app/admins"
import { Route as AppAssignmentRouteImport } from "./routes/_app/assignment"
import { Route as AppCourierPayoutsRouteImport } from "./routes/_app/courier-payouts"
import { Route as AppCouriersRouteImport } from "./routes/_app/couriers"
import { Route as AppDashboardRouteImport } from "./routes/_app/dashboard"
import { Route as AppProfileRouteImport } from "./routes/_app/profile"
import { Route as AppRevenueRouteImport } from "./routes/_app/revenue"
import { Route as AppSettingsRouteImport } from "./routes/_app/settings"
import { Route as AppSmesRouteImport } from "./routes/_app/smes"
import { Route as AppUsersRouteImport } from "./routes/_app/users"
import { Route as AppNodesIndexRouteImport } from "./routes/_app/nodes/index"
import { Route as AppNodesNodeIdRouteImport } from "./routes/_app/nodes/$nodeId"
import { Route as AppWorkloadsIndexRouteImport } from "./routes/_app/workloads/index"
import { Route as AppWorkloadsBatchesBatchIdRouteImport } from "./routes/_app/workloads/batches/$batchId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSetupRoute = AccountSetupRouteImport.update({
  id: "/account-setup",
  path: "/account-setup",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminsRoute = AppAdminsRouteImport.update({
  id: "/admins",
  path: "/admins",
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentRoute = AppAssignmentRouteImport.update({
  id: "/assignment",
  path: "/assignment",
  getParentRoute: () => AppRoute,
} as any)
const AppCourierPayoutsRoute = AppCourierPayoutsRouteImport.update({
  id: "/courier-payouts",
  path: "/courier-payouts",
  getParentRoute: () => AppRoute,
} as any)
const AppCouriersRoute = AppCouriersRouteImport.update({
  id: "/couriers",
  path: "/couriers",
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueRoute = AppRevenueRouteImport.update({
  id: "/revenue",
  path: "/revenue",
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any)
const AppSmesRoute = AppSmesRouteImport.update({
  id: "/smes",
  path: "/smes",
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AppRoute,
} as any)
const AppNodesIndexRoute = AppNodesIndexRouteImport.update({
  id: "/nodes/",
  path: "/nodes/",
  getParentRoute: () => AppRoute,
} as any)
const AppNodesNodeIdRoute = AppNodesNodeIdRouteImport.update({
  id: "/nodes/$nodeId",
  path: "/nodes/$nodeId",
  getParentRoute: () => AppRoute,
} as any)
const AppWorkloadsIndexRoute = AppWorkloadsIndexRouteImport.update({
  id: "/workloads/",
  path: "/workloads/",
  getParentRoute: () => AppRoute,
} as any)
const AppWorkloadsBatchesBatchIdRoute =
  AppWorkloadsBatchesBatchIdRouteImport.update({
    id: "/workloads/batches/$batchId",
    path: "/workloads/batches/$batchId",
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/account-setup": typeof AccountSetupRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/reset-password": typeof ResetPasswordRoute
  "/admins": typeof AppAdminsRoute
  "/assignment": typeof AppAssignmentRoute
  "/courier-payouts": typeof AppCourierPayoutsRoute
  "/couriers": typeof AppCouriersRoute
  "/dashboard": typeof AppDashboardRoute
  "/profile": typeof AppProfileRoute
  "/revenue": typeof AppRevenueRoute
  "/settings": typeof AppSettingsRoute
  "/smes": typeof AppSmesRoute
  "/users": typeof AppUsersRoute
  "/nodes/$nodeId": typeof AppNodesNodeIdRoute
  "/nodes/": typeof AppNodesIndexRoute
  "/workloads/": typeof AppWorkloadsIndexRoute
  "/workloads/batches/$batchId": typeof AppWorkloadsBatchesBatchIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/account-setup": typeof AccountSetupRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/reset-password": typeof ResetPasswordRoute
  "/admins": typeof AppAdminsRoute
  "/assignment": typeof AppAssignmentRoute
  "/courier-payouts": typeof AppCourierPayoutsRoute
  "/couriers": typeof AppCouriersRoute
  "/dashboard": typeof AppDashboardRoute
  "/profile": typeof AppProfileRoute
  "/revenue": typeof AppRevenueRoute
  "/settings": typeof AppSettingsRoute
  "/smes": typeof AppSmesRoute
  "/users": typeof AppUsersRoute
  "/nodes/$nodeId": typeof AppNodesNodeIdRoute
  "/nodes": typeof AppNodesIndexRoute
  "/workloads": typeof AppWorkloadsIndexRoute
  "/workloads/batches/$batchId": typeof AppWorkloadsBatchesBatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/_app": typeof AppRouteWithChildren
  "/account-setup": typeof AccountSetupRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/reset-password": typeof ResetPasswordRoute
  "/_app/admins": typeof AppAdminsRoute
  "/_app/assignment": typeof AppAssignmentRoute
  "/_app/courier-payouts": typeof AppCourierPayoutsRoute
  "/_app/couriers": typeof AppCouriersRoute
  "/_app/dashboard": typeof AppDashboardRoute
  "/_app/profile": typeof AppProfileRoute
  "/_app/revenue": typeof AppRevenueRoute
  "/_app/settings": typeof AppSettingsRoute
  "/_app/smes": typeof AppSmesRoute
  "/_app/users": typeof AppUsersRoute
  "/_app/nodes/$nodeId": typeof AppNodesNodeIdRoute
  "/_app/nodes/": typeof AppNodesIndexRoute
  "/_app/workloads/": typeof AppWorkloadsIndexRoute
  "/_app/workloads/batches/$batchId": typeof AppWorkloadsBatchesBatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/$"
    | "/account-setup"
    | "/forgot-password"
    | "/reset-password"
    | "/admins"
    | "/assignment"
    | "/courier-payouts"
    | "/couriers"
    | "/dashboard"
    | "/profile"
    | "/revenue"
    | "/settings"
    | "/smes"
    | "/users"
    | "/nodes/$nodeId"
    | "/nodes/"
    | "/workloads/"
    | "/workloads/batches/$batchId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/$"
    | "/account-setup"
    | "/forgot-password"
    | "/reset-password"
    | "/admins"
    | "/assignment"
    | "/courier-payouts"
    | "/couriers"
    | "/dashboard"
    | "/profile"
    | "/revenue"
    | "/settings"
    | "/smes"
    | "/users"
    | "/nodes/$nodeId"
    | "/nodes"
    | "/workloads"
    | "/workloads/batches/$batchId"
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/_app"
    | "/account-setup"
    | "/forgot-password"
    | "/reset-password"
    | "/_app/admins"
    | "/_app/assignment"
    | "/_app/courier-payouts"
    | "/_app/couriers"
    | "/_app/dashboard"
    | "/_app/profile"
    | "/_app/revenue"
    | "/_app/settings"
    | "/_app/smes"
    | "/_app/users"
    | "/_app/nodes/$nodeId"
    | "/_app/nodes/"
    | "/_app/workloads/"
    | "/_app/workloads/batches/$batchId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  AccountSetupRoute: typeof AccountSetupRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$": {
      id: "/$"
      path: "/$"
      fullPath: "/$"
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/account-setup": {
      id: "/account-setup"
      path: "/account-setup"
      fullPath: "/account-setup"
      preLoaderRoute: typeof AccountSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password": {
      id: "/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/admins": {
      id: "/_app/admins"
      path: "/admins"
      fullPath: "/admins"
      preLoaderRoute: typeof AppAdminsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/assignment": {
      id: "/_app/assignment"
      path: "/assignment"
      fullPath: "/assignment"
      preLoaderRoute: typeof AppAssignmentRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/courier-payouts": {
      id: "/_app/courier-payouts"
      path: "/courier-payouts"
      fullPath: "/courier-payouts"
      preLoaderRoute: typeof AppCourierPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/couriers": {
      id: "/_app/couriers"
      path: "/couriers"
      fullPath: "/couriers"
      preLoaderRoute: typeof AppCouriersRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/dashboard": {
      id: "/_app/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/profile": {
      id: "/_app/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/revenue": {
      id: "/_app/revenue"
      path: "/revenue"
      fullPath: "/revenue"
      preLoaderRoute: typeof AppRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings": {
      id: "/_app/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/smes": {
      id: "/_app/smes"
      path: "/smes"
      fullPath: "/smes"
      preLoaderRoute: typeof AppSmesRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/users": {
      id: "/_app/users"
      path: "/users"
      fullPath: "/users"
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/nodes/": {
      id: "/_app/nodes/"
      path: "/nodes"
      fullPath: "/nodes/"
      preLoaderRoute: typeof AppNodesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/nodes/$nodeId": {
      id: "/_app/nodes/$nodeId"
      path: "/nodes/$nodeId"
      fullPath: "/nodes/$nodeId"
      preLoaderRoute: typeof AppNodesNodeIdRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/workloads/": {
      id: "/_app/workloads/"
      path: "/workloads"
      fullPath: "/workloads/"
      preLoaderRoute: typeof AppWorkloadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/workloads/batches/$batchId": {
      id: "/_app/workloads/batches/$batchId"
      path: "/workloads/batches/$batchId"
      fullPath: "/workloads/batches/$batchId"
      preLoaderRoute: typeof AppWorkloadsBatchesBatchIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminsRoute: typeof AppAdminsRoute
  AppAssignmentRoute: typeof AppAssignmentRoute
  AppCourierPayoutsRoute: typeof AppCourierPayoutsRoute
  AppCouriersRoute: typeof AppCouriersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRevenueRoute: typeof AppRevenueRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSmesRoute: typeof AppSmesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppNodesNodeIdRoute: typeof AppNodesNodeIdRoute
  AppNodesIndexRoute: typeof AppNodesIndexRoute
  AppWorkloadsIndexRoute: typeof AppWorkloadsIndexRoute
  AppWorkloadsBatchesBatchIdRoute: typeof AppWorkloadsBatchesBatchIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminsRoute: AppAdminsRoute,
  AppAssignmentRoute: AppAssignmentRoute,
  AppCourierPayoutsRoute: AppCourierPayoutsRoute,
  AppCouriersRoute: AppCouriersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppRevenueRoute: AppRevenueRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSmesRoute: AppSmesRoute,
  AppUsersRoute: AppUsersRoute,
  AppNodesNodeIdRoute: AppNodesNodeIdRoute,
  AppNodesIndexRoute: AppNodesIndexRoute,
  AppWorkloadsIndexRoute: AppWorkloadsIndexRoute,
  AppWorkloadsBatchesBatchIdRoute: AppWorkloadsBatchesBatchIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  AccountSetupRoute: AccountSetupRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
