export const trackingContent = {
  heading: "Where's your parcel right now?",
  subhead: "Enter your Alvo tracking code for a live status update.",
  inputPlaceholder: "Enter tracking code - e.g PRV-4KC-9XQ",
  trackCta: "Track",
  quickActions: [
    {label: "How to collect", icon: "lock", href: "/help"},
    {label: "Send a parcel", icon: "send", href: "/"},
    {label: "Contact a support", icon: "mail", href: "mailto:support@alvo.com"},
  ],
  successCode: "PRV-4K2-9XQ",
  result: {
    trackingId: "#PRV-4K2-9XQ",
    status: "In transit",
    summary: "In transit — on the way",
    destination: {label: "Destination locker", value: "Yaba hub · Bay"},
    eta: {label: "Estimated arrival", value: "Today, 11:35"},
    stops: {label: "Stops remaining", value: "2"},
    mapAlt: "Map showing live parcel route and nearby Alvo lockers",
    mapSrc: "/tracking/map.png",
    timeline: [
      {title: "Booking confirmed", detail: "09:02 · Tracking ID issued", completed: true},
      {title: "Dropped at locker", detail: "09:14 · Lekki Phase 1 · Bay 07", completed: true},
      {title: "Courier collected", detail: "09:41 · Route 7 assigned", completed: true},
      {title: "On the way", detail: "Now · 2 stops remaining", completed: true},
      {title: "Ready for pickup", detail: "Yaba hub locker · collect with your code", completed: false},
    ],
  },
  notFound: {
    icon: "/tracking/location-not-found.svg",
    iconAlt: "Location not found",
    heading: "No parcel found",
    message: "Double-check your tracking code. It usually looks like ",
    code: "PRV-4K2-9XQ",
    suffix: ". If you think there's an issue, ",
    support: "contact support",
    supportHref: "mailto:support@alvo.com",
    end: ".",
  },
} as const;
